name: CI
on:
  push:
    branches:
      - main
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        
    - name: Install and Build
      run: |
        npm install
        npm run build
     
    - name: Deploy
      with:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        HOST: ${{ secrets.HOST }}
        FOLDER: dist
      run: |
        mkdir -p .ssh
        chmod 700 .ssh
        echo "$SSH_KEY" >> .ssh/rsa
        chmod 700 .ssh/rsa
        sftp -o StrictHostKeyChecking=no -i .ssh/rsa $HOST -tt "
        put -r $FOLDER million-singer/
        "
        ssh -o StrictHostKeyChecking=no -i .ssh/rsa $HOST -tt "
        cd million-singer
        docker-build -d --build
        rm -rf dist
        "
